# Generated by Django 3.2.18 on 2023-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('result', models.TextField(blank=True, null=True)),
                ('exception', models.CharField(blank=True, max_length=128, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
